name: fina_points_calculator
description: "App for calculations between time and aqua points."
publish_to: "none"
version: 1.3.9+17

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  go_router: ^16.2.0
  intl: any
  material_symbols_icons: ^4.2785.1
  provider: ^6.1.2
  rename_app: ^1.6.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  inno_bundle: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/flags/
    - assets/table_base_times/22-23/
    - assets/table_base_times/23-24/
    - assets/table_base_times/24-25/
    - assets/table_base_times/25-26/
    - assets/wr_times/
    - assets/limit_times/
    - assets/
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon/app_icon.png"

inno_bundle:
  id: 90636bc0-0d68-11f0-a960-759483543004
  publisher: Vojtech Netrh
  version: 1.3.1
  url: https://github.com/Nert53/aqua-points-calculator/blob/main/README.md
  updates_url: https://github.com/Nert53/aqua-points-calculator/releases
  installer_icon: assets/app_icon/installer_icon.ico
  languages:
    - english
    - german
    - czech
    - italian
  admin: auto
